/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
};

export type ServicesOverview = {
  _id: string;
  _type: "servicesOverview";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
};

export type Employee = {
  _id: string;
  _type: "employee";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  title?: string;
  photo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  description?: string;
  email?: string;
};

export type AboutInfo = {
  _id: string;
  _type: "aboutInfo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
};

export type ContactInfo = {
  _id: string;
  _type: "contactInfo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  email?: string;
  phone?: string;
  location?: string;
  slogan?: string;
};

export type ProjectsOverview = {
  _id: string;
  _type: "projectsOverview";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
};

export type Projects = {
  _id: string;
  _type: "projects";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  location?: string;
  date?: string;
  eventType?: string;
  description?: string;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  showOnFrontpage?: boolean;
  slug?: Slug;
};

export type ShortInfo = {
  _id: string;
  _type: "shortInfo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes = Service | ServicesOverview | Employee | AboutInfo | ContactInfo | ProjectsOverview | Projects | ShortInfo | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityImageAsset | SanityImageMetadata | Geopoint | Slug | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/sanity/lib/queries.ts
// Variable: projectsOverviewQuery
// Query: *[_type == "projectsOverview"][0]{  title,  description}
export type ProjectsOverviewQueryResult = {
  title: string | null;
  description: string | null;
} | null;
// Variable: allProjectsQuery
// Query: *[_type == "projects"] | order(date desc){  _id,  title,  location,  description,  date,  slug,  showOnFrontpage,  images[],  _type,  _createdAt,  _updatedAt,  _rev}
export type AllProjectsQueryResult = Array<{
  _id: string;
  title: string | null;
  location: string | null;
  description: string | null;
  date: string | null;
  slug: Slug | null;
  showOnFrontpage: boolean | null;
  images: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }> | null;
  _type: "projects";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
}>;
// Variable: projectBySlugQuery
// Query: *[_type == "projects" && slug.current == $slug][0]{  _id,  title,  location,  description,  date,  slug,  showOnFrontpage,  images[],  client,  eventType,  _type,  _createdAt,  _updatedAt,  _rev}
export type ProjectBySlugQueryResult = {
  _id: string;
  title: string | null;
  location: string | null;
  description: string | null;
  date: string | null;
  slug: Slug | null;
  showOnFrontpage: boolean | null;
  images: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }> | null;
  client: null;
  eventType: string | null;
  _type: "projects";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
} | null;
// Variable: shortInfoQuery
// Query: *[_type == "shortInfo"][0]{  title,  description,  image,}
export type ShortInfoQueryResult = {
  title: string | null;
  description: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
} | null;
// Variable: aboutInfoQuery
// Query: *[_type == "aboutInfo"][0]{  title,  description,}
export type AboutInfoQueryResult = {
  title: string | null;
  description: string | null;
} | null;
// Variable: allEmployeesQuery
// Query: *[_type == "employee"]{  _id,  name,  title,  photo,  description,  email}
export type AllEmployeesQueryResult = Array<{
  _id: string;
  name: string | null;
  title: string | null;
  photo: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  description: string | null;
  email: string | null;
}>;
// Variable: contactInfoQuery
// Query: *[_type == "contactInfo"][0]{  email,  phone,  location,  slogan}
export type ContactInfoQueryResult = {
  email: string | null;
  phone: string | null;
  location: string | null;
  slogan: string | null;
} | null;
// Variable: servicesOverviewQuery
// Query: *[_type == "servicesOverview"][0]{  title,  description}
export type ServicesOverviewQueryResult = {
  title: string | null;
  description: string | null;
} | null;
// Variable: allServicesQuery
// Query: *[_type == "service"] | order(_createdAt asc){  title,  description  }
export type AllServicesQueryResult = Array<{
  title: string | null;
  description: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == \"projectsOverview\"][0]{\n  title,\n  description\n}": ProjectsOverviewQueryResult;
    "*[_type == \"projects\"] | order(date desc){\n  _id,\n  title,\n  location,\n  description,\n  date,\n  slug,\n  showOnFrontpage,\n  images[],\n  _type,\n  _createdAt,\n  _updatedAt,\n  _rev\n}": AllProjectsQueryResult;
    "*[_type == \"projects\" && slug.current == $slug][0]{\n  _id,\n  title,\n  location,\n  description,\n  date,\n  slug,\n  showOnFrontpage,\n  images[],\n  client,\n  eventType,\n  _type,\n  _createdAt,\n  _updatedAt,\n  _rev\n}": ProjectBySlugQueryResult;
    "*[_type == \"shortInfo\"][0]{\n  title,\n  description,\n  image,\n}": ShortInfoQueryResult;
    "*[_type == \"aboutInfo\"][0]{\n  title,\n  description,\n}": AboutInfoQueryResult;
    "*[_type == \"employee\"]{\n  _id,\n  name,\n  title,\n  photo,\n  description,\n  email\n}": AllEmployeesQueryResult;
    "*[_type == \"contactInfo\"][0]{\n  email,\n  phone,\n  location,\n  slogan\n}": ContactInfoQueryResult;
    "*[_type == \"servicesOverview\"][0]{\n  title,\n  description\n}": ServicesOverviewQueryResult;
    "*[_type == \"service\"] | order(_createdAt asc){\n  title,\n  description\n  }": AllServicesQueryResult;
  }
}
